#!/usr/bin/env python3
"""
generate-sitemap.py — bhapstar
-------------------------------------------------------------
Rebuilds sitemap.xml from site-data.json so the page/image list never
goes stale. Run by the GitHub Action on every push, or by hand:

    python generate-sitemap.py

- site-data.json holds gallery, gear and article entries, tagged with a
  "section" field ("gallery", "gear" or "article").
- Gallery images are listed under gallery.html; gear images under
  gear.html. Each set is de-duplicated (shared files counted once).
- Every gear/<slug>.html and articles/<slug>.html page is listed
  individually, skipping anything flagged "hidden".
- Every share/<slug>.html page is listed individually (these are real,
  indexable per-image pages generated by generate-share-pages.py),
  each carrying its own image entries and its entry's real date.
- <lastmod> uses REAL dates derived from entry dates in site-data.json,
  never "today" — stamping the deploy date on everything teaches Google
  to ignore the signal entirely:
      home + gallery  -> newest gallery entry date
      share pages     -> that entry's own date
      articles        -> that article's own date
      everything else -> STATIC_LASTMOD (bump it if a page has a real
                         content change worth signalling)
- field_notes.html is deliberately NOT listed: the page is retired from
  navigation (HIDE_FIELD_NOTES) and marked noindex; its content now
  lives on the share pages.
"""

import json
import sys
import datetime
from urllib.parse import quote

DOMAIN = "https://bhapstar.com/"
DATA = "site-data.json"
OUT = "sitemap.xml"
SHARE_DIR = "share"
GEAR_DIR = "gear"
GEAR_REVIEWS_DIR = "gear-reviews"
ARTICLE_DIR = "articles"

# (path, changefreq, priority, image_section)
# image_section: None = no images, else the "section" whose images go here.
PAGES = [
    ("",                        "monthly",  "1.0",  None),
    ("gallery.html",            "monthly",  "0.9",  "gallery"),
    ("gear.html",               "monthly",  "0.8",  "gear"),
    ("articles.html",           "monthly",  "0.8",  None),
    ("prints.html",             "monthly",  "0.7",  None),
    ("jigsaw.html",             "yearly",   "0.6",  None),
    ("quiz.html",               "yearly",   "0.6",  None),
    ("star_word.html",          "yearly",   "0.6",  None),
    ("supernova_sweeper.html",  "yearly",   "0.6",  None),
]
STATIC_LASTMOD = "2025-04-20"

SHARE_CHANGEFREQ = "yearly"   # a photo's page rarely changes once published
SHARE_PRIORITY = "0.7"

# Articles get a higher priority than a single photo page: they are the pages
# most likely to be the reason somebody arrives from a search engine.
ARTICLE_CHANGEFREQ = "yearly"
ARTICLE_PRIORITY = "0.8"


def to_iso(date_str):
    """Convert 'DD-MM-YYYY' to ISO 'YYYY-MM-DD'. Falls back to None."""
    try:
        return datetime.datetime.strptime(date_str, "%d-%m-%Y").strftime("%Y-%m-%d")
    except (TypeError, ValueError):
        return None


def entry_files(it):
    """Every image file belonging to an entry (single file, images[], video posters)."""
    files = []
    if it.get("file"):
        files.append(it["file"])
    for im in it.get("images", []) or []:
        if im.get("file"):
            files.append(im["file"])
    for v in it.get("videos", []) or []:
        if v.get("poster"):
            files.append(v["poster"])
    return files


def collect_images(items):
    urls = []
    for it in items:
        for f in entry_files(it):
            u = DOMAIN + quote(f)
            if u not in urls:
                urls.append(u)
    return urls


def has_cover(it):
    """Check if entry has a cover image."""
    return bool(it.get("file") or (it.get("images") and len(it["images"]) > 0))


def has_review(slug):
    """Check if gear-reviews/<slug>.html exists."""
    import os
    path = os.path.join(GEAR_REVIEWS_DIR, f"{slug}.html")
    return os.path.isfile(path)


def image_block(urls, indent="    "):
    return "\n".join(
        f"{indent}<image:image>\n{indent}  <image:loc>{u}</image:loc>\n{indent}</image:image>"
        for u in urls
    )


def newest_date(items):
    """Most recent valid entry date in the given items, or None."""
    dates = [d for d in (to_iso(it.get("date")) for it in items) if d]
    return max(dates) if dates else None


def has_cover(it):
    """Mirrors generate-share-pages.py: an entry gets a share page only if it
    has a slug and at least one image/poster."""
    imgs = it.get("images")
    if imgs and imgs[0].get("file"):
        return True
    if it.get("file"):
        return True
    vids = it.get("videos")
    return bool(vids and vids[0].get("poster"))


def url_entry(out, loc, lastmod, freq, prio, img_urls=None):
    out.append("  <url>")
    out.append(f"    <loc>{loc}</loc>")
    out.append(f"    <lastmod>{lastmod}</lastmod>")
    out.append(f"    <changefreq>{freq}</changefreq>")
    out.append(f"    <priority>{prio}</priority>")
    if img_urls:
        out.append(image_block(img_urls))
    out.append("  </url>")


def main():
    with open(DATA, encoding="utf-8") as fh:
        items = json.load(fh)

    gallery_items = [it for it in items if (it.get("section") or "gallery") == "gallery"]
    gear_items = [it for it in items if (it.get("section") or "gallery") == "gear"]
    article_items = [it for it in items
                     if it.get("section") == "article"
                     and it.get("slug") and not it.get("hidden")]

    newest_gallery = newest_date(gallery_items) or STATIC_LASTMOD
    newest_gear = newest_date(gear_items) or STATIC_LASTMOD
    newest_article = newest_date(article_items) or STATIC_LASTMOD

    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
    ]

    counts = {}
    for path, freq, prio, section in PAGES:
        if path == "" or path == "gallery.html":
            lastmod = newest_gallery
        elif path == "gear.html":
            lastmod = newest_gear
        elif path == "articles.html":
            lastmod = newest_article
        else:
            lastmod = STATIC_LASTMOD

        img_urls = None
        if section:
            sect = gallery_items if section == "gallery" else gear_items
            img_urls = collect_images(sect)
            counts[section] = len(img_urls)

        url_entry(out, DOMAIN + path, lastmod, freq, prio, img_urls)

    # ── Per-image share pages ──
    share_count = 0
    for it in gallery_items:
        slug = it.get("slug")
        if not slug or not has_cover(it):
            continue
        loc = f"{DOMAIN}{SHARE_DIR}/{quote(slug)}.html"
        lastmod = to_iso(it.get("date")) or STATIC_LASTMOD
        img_urls = [DOMAIN + quote(f) for f in entry_files(it)]
        url_entry(out, loc, lastmod, SHARE_CHANGEFREQ, SHARE_PRIORITY, img_urls)
        share_count += 1

    # ── Per-gear pages (all gear items get a page) ──
    gear_count = 0
    for it in items:
        if it.get("section") != "gear":
            continue
        slug = it.get("slug")
        if not slug or it.get("hidden"):
            continue
        loc = f"{DOMAIN}{GEAR_DIR}/{quote(slug)}.html"
        lastmod = STATIC_LASTMOD  # gear pages don't track dates in site-data
        img_urls = [DOMAIN + quote(f) for f in entry_files(it)]
        url_entry(out, loc, lastmod, SHARE_CHANGEFREQ, SHARE_PRIORITY, img_urls)
        gear_count += 1

    # ── Per-article pages ──
    article_count = 0
    for it in article_items:
        loc = f"{DOMAIN}{ARTICLE_DIR}/{quote(it['slug'])}.html"
        lastmod = to_iso(it.get("date")) or STATIC_LASTMOD
        img_urls = [DOMAIN + quote(f) for f in entry_files(it)]
        url_entry(out, loc, lastmod, ARTICLE_CHANGEFREQ, ARTICLE_PRIORITY, img_urls)
        article_count += 1

    out.append("</urlset>")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")

    print(f"Wrote {OUT}: {len(PAGES)} pages + {share_count} share pages + "
          f"{gear_count} gear pages + {article_count} article pages; "
          f"images by section: {counts}")


if __name__ == "__main__":
    sys.exit(main())
