#!/usr/bin/env bash
# Renames gallery images to slug-based filenames.
# Run from the ROOT of your public site repo (where images/ lives).
# Uses git mv so history is preserved. Review with git status before committing.
set -e

[ -f "images/Rosette Nebula.webp" ] && git mv "images/Rosette Nebula.webp" "images/rosette-nebula-ngc2244.webp" || echo "skip (not found): images/Rosette Nebula.webp"
[ -f "images/thumbs/Rosette Nebula.webp" ] && git mv "images/thumbs/Rosette Nebula.webp" "images/thumbs/rosette-nebula-ngc2244.webp" || echo "skip (not found): images/thumbs/Rosette Nebula.webp"
[ -f "images/Eagle Nebula.webp" ] && git mv "images/Eagle Nebula.webp" "images/eagle-nebula-m16-1.webp" || echo "skip (not found): images/Eagle Nebula.webp"
[ -f "images/thumbs/Eagle Nebula.webp" ] && git mv "images/thumbs/Eagle Nebula.webp" "images/thumbs/eagle-nebula-m16-1.webp" || echo "skip (not found): images/thumbs/Eagle Nebula.webp"
[ -f "images/Eagle Nebula 2.webp" ] && git mv "images/Eagle Nebula 2.webp" "images/eagle-nebula-m16-2.webp" || echo "skip (not found): images/Eagle Nebula 2.webp"
[ -f "images/thumbs/Eagle Nebula 2.webp" ] && git mv "images/thumbs/Eagle Nebula 2.webp" "images/thumbs/eagle-nebula-m16-2.webp" || echo "skip (not found): images/thumbs/Eagle Nebula 2.webp"
[ -f "images/Jellyfish Nebula.webp" ] && git mv "images/Jellyfish Nebula.webp" "images/jellyfish-nebula-ic443.webp" || echo "skip (not found): images/Jellyfish Nebula.webp"
[ -f "images/thumbs/Jellyfish Nebula.webp" ] && git mv "images/thumbs/Jellyfish Nebula.webp" "images/thumbs/jellyfish-nebula-ic443.webp" || echo "skip (not found): images/thumbs/Jellyfish Nebula.webp"
[ -f "images/Xmas.webp" ] && git mv "images/Xmas.webp" "images/christmas-tree-nebula-ngc2264.webp" || echo "skip (not found): images/Xmas.webp"
[ -f "images/thumbs/Xmas.webp" ] && git mv "images/thumbs/Xmas.webp" "images/thumbs/christmas-tree-nebula-ngc2264.webp" || echo "skip (not found): images/thumbs/Xmas.webp"
[ -f "images/Pleiades.webp" ] && git mv "images/Pleiades.webp" "images/pleiades-m45.webp" || echo "skip (not found): images/Pleiades.webp"
[ -f "images/thumbs/Pleiades.webp" ] && git mv "images/thumbs/Pleiades.webp" "images/thumbs/pleiades-m45.webp" || echo "skip (not found): images/thumbs/Pleiades.webp"
[ -f "images/Orion Nebula.webp" ] && git mv "images/Orion Nebula.webp" "images/orion-nebula-m42.webp" || echo "skip (not found): images/Orion Nebula.webp"
[ -f "images/thumbs/Orion Nebula.webp" ] && git mv "images/thumbs/Orion Nebula.webp" "images/thumbs/orion-nebula-m42.webp" || echo "skip (not found): images/thumbs/Orion Nebula.webp"
[ -f "images/Flame&Horsehead.webp" ] && git mv "images/Flame&Horsehead.webp" "images/flame-horsehead-nebulae.webp" || echo "skip (not found): images/Flame&Horsehead.webp"
[ -f "images/thumbs/Flame&Horsehead.webp" ] && git mv "images/thumbs/Flame&Horsehead.webp" "images/thumbs/flame-horsehead-nebulae.webp" || echo "skip (not found): images/thumbs/Flame&Horsehead.webp"
[ -f "images/Andromeda.webp" ] && git mv "images/Andromeda.webp" "images/andromeda-galaxy-m31.webp" || echo "skip (not found): images/Andromeda.webp"
[ -f "images/thumbs/Andromeda.webp" ] && git mv "images/thumbs/Andromeda.webp" "images/thumbs/andromeda-galaxy-m31.webp" || echo "skip (not found): images/thumbs/Andromeda.webp"
[ -f "images/Monkeyhead Nebula.webp" ] && git mv "images/Monkeyhead Nebula.webp" "images/monkey-head-nebula-ngc2174.webp" || echo "skip (not found): images/Monkeyhead Nebula.webp"
[ -f "images/thumbs/Monkeyhead Nebula.webp" ] && git mv "images/thumbs/Monkeyhead Nebula.webp" "images/thumbs/monkey-head-nebula-ngc2174.webp" || echo "skip (not found): images/thumbs/Monkeyhead Nebula.webp"
[ -f "images/Needle Galaxy.webp" ] && git mv "images/Needle Galaxy.webp" "images/needle-galaxy-ngc4565.webp" || echo "skip (not found): images/Needle Galaxy.webp"
[ -f "images/thumbs/Needle Galaxy.webp" ] && git mv "images/thumbs/Needle Galaxy.webp" "images/thumbs/needle-galaxy-ngc4565.webp" || echo "skip (not found): images/thumbs/Needle Galaxy.webp"
[ -f "images/The Moon_1.webp" ] && git mv "images/The Moon_1.webp" "images/the-moon-1.webp" || echo "skip (not found): images/The Moon_1.webp"
[ -f "images/thumbs/The Moon_1.webp" ] && git mv "images/thumbs/The Moon_1.webp" "images/thumbs/the-moon-1.webp" || echo "skip (not found): images/thumbs/The Moon_1.webp"
[ -f "images/The Moon_2.webp" ] && git mv "images/The Moon_2.webp" "images/the-moon-2.webp" || echo "skip (not found): images/The Moon_2.webp"
[ -f "images/thumbs/The Moon_2.webp" ] && git mv "images/thumbs/The Moon_2.webp" "images/thumbs/the-moon-2.webp" || echo "skip (not found): images/thumbs/The Moon_2.webp"
[ -f "images/The Moon_3.webp" ] && git mv "images/The Moon_3.webp" "images/the-moon-3.webp" || echo "skip (not found): images/The Moon_3.webp"
[ -f "images/thumbs/The Moon_3.webp" ] && git mv "images/thumbs/The Moon_3.webp" "images/thumbs/the-moon-3.webp" || echo "skip (not found): images/thumbs/The Moon_3.webp"
[ -f "images/Bodes & Cigar.webp" ] && git mv "images/Bodes & Cigar.webp" "images/bodes-cigar-galaxies-m81-m82-1.webp" || echo "skip (not found): images/Bodes & Cigar.webp"
[ -f "images/thumbs/Bodes & Cigar.webp" ] && git mv "images/thumbs/Bodes & Cigar.webp" "images/thumbs/bodes-cigar-galaxies-m81-m82-1.webp" || echo "skip (not found): images/thumbs/Bodes & Cigar.webp"
[ -f "images/Bodes & Cigar 2.webp" ] && git mv "images/Bodes & Cigar 2.webp" "images/bodes-cigar-galaxies-m81-m82-2.webp" || echo "skip (not found): images/Bodes & Cigar 2.webp"
[ -f "images/thumbs/Bodes & Cigar 2.webp" ] && git mv "images/thumbs/Bodes & Cigar 2.webp" "images/thumbs/bodes-cigar-galaxies-m81-m82-2.webp" || echo "skip (not found): images/thumbs/Bodes & Cigar 2.webp"
[ -f "images/Pinwheel.webp" ] && git mv "images/Pinwheel.webp" "images/pinwheel-galaxy-m101.webp" || echo "skip (not found): images/Pinwheel.webp"
[ -f "images/thumbs/Pinwheel.webp" ] && git mv "images/thumbs/Pinwheel.webp" "images/thumbs/pinwheel-galaxy-m101.webp" || echo "skip (not found): images/thumbs/Pinwheel.webp"
[ -f "images/Leo Triplet.webp" ] && git mv "images/Leo Triplet.webp" "images/leo-triplet-m65-m66-ngc3628.webp" || echo "skip (not found): images/Leo Triplet.webp"
[ -f "images/thumbs/Leo Triplet.webp" ] && git mv "images/thumbs/Leo Triplet.webp" "images/thumbs/leo-triplet-m65-m66-ngc3628.webp" || echo "skip (not found): images/thumbs/Leo Triplet.webp"
[ -f "images/Thors-Helmet.webp" ] && git mv "images/Thors-Helmet.webp" "images/thors-helmet-ngc2359.webp" || echo "skip (not found): images/Thors-Helmet.webp"
[ -f "images/thumbs/Thors-Helmet.webp" ] && git mv "images/thumbs/Thors-Helmet.webp" "images/thumbs/thors-helmet-ngc2359.webp" || echo "skip (not found): images/thumbs/Thors-Helmet.webp"
[ -f "images/Little Beehive Cluster.webp" ] && git mv "images/Little Beehive Cluster.webp" "images/little-beehive-cluster-m41.webp" || echo "skip (not found): images/Little Beehive Cluster.webp"
[ -f "images/thumbs/Little Beehive Cluster.webp" ] && git mv "images/thumbs/Little Beehive Cluster.webp" "images/thumbs/little-beehive-cluster-m41.webp" || echo "skip (not found): images/thumbs/Little Beehive Cluster.webp"
[ -f "images/Triangulum.webp" ] && git mv "images/Triangulum.webp" "images/triangulum-galaxy-m33.webp" || echo "skip (not found): images/Triangulum.webp"
[ -f "images/thumbs/Triangulum.webp" ] && git mv "images/thumbs/Triangulum.webp" "images/thumbs/triangulum-galaxy-m33.webp" || echo "skip (not found): images/thumbs/Triangulum.webp"
[ -f "images/MilkyWay&Me.webp" ] && git mv "images/MilkyWay&Me.webp" "images/milky-way-and-me-1.webp" || echo "skip (not found): images/MilkyWay&Me.webp"
[ -f "images/thumbs/MilkyWay&Me.webp" ] && git mv "images/thumbs/MilkyWay&Me.webp" "images/thumbs/milky-way-and-me-1.webp" || echo "skip (not found): images/thumbs/MilkyWay&Me.webp"
[ -f "images/MilkyWay&Me2.webp" ] && git mv "images/MilkyWay&Me2.webp" "images/milky-way-and-me-2.webp" || echo "skip (not found): images/MilkyWay&Me2.webp"
[ -f "images/thumbs/MilkyWay&Me2.webp" ] && git mv "images/thumbs/MilkyWay&Me2.webp" "images/thumbs/milky-way-and-me-2.webp" || echo "skip (not found): images/thumbs/MilkyWay&Me2.webp"
[ -f "images/MilkyWay&Me3.webp" ] && git mv "images/MilkyWay&Me3.webp" "images/milky-way-and-me-3.webp" || echo "skip (not found): images/MilkyWay&Me3.webp"
[ -f "images/thumbs/MilkyWay&Me3.webp" ] && git mv "images/thumbs/MilkyWay&Me3.webp" "images/thumbs/milky-way-and-me-3.webp" || echo "skip (not found): images/thumbs/MilkyWay&Me3.webp"
[ -f "images/MilkyWay&Me4.webp" ] && git mv "images/MilkyWay&Me4.webp" "images/milky-way-and-me-4.webp" || echo "skip (not found): images/MilkyWay&Me4.webp"
[ -f "images/thumbs/MilkyWay&Me4.webp" ] && git mv "images/thumbs/MilkyWay&Me4.webp" "images/thumbs/milky-way-and-me-4.webp" || echo "skip (not found): images/thumbs/MilkyWay&Me4.webp"
[ -f "images/Geminids_Composite.webp" ] && git mv "images/Geminids_Composite.webp" "images/geminids-meteor-shower.webp" || echo "skip (not found): images/Geminids_Composite.webp"
[ -f "images/thumbs/Geminids_Composite.webp" ] && git mv "images/thumbs/Geminids_Composite.webp" "images/thumbs/geminids-meteor-shower.webp" || echo "skip (not found): images/thumbs/Geminids_Composite.webp"
[ -f "images/Geminids_Composite_Labelled.webp" ] && git mv "images/Geminids_Composite_Labelled.webp" "images/geminids-meteor-shower-labelled.webp" || echo "skip (not found): images/Geminids_Composite_Labelled.webp"
[ -f "images/thumbs/Geminids_Composite_Labelled.webp" ] && git mv "images/thumbs/Geminids_Composite_Labelled.webp" "images/thumbs/geminids-meteor-shower-labelled.webp" || echo "skip (not found): images/thumbs/Geminids_Composite_Labelled.webp"
[ -f "images/startrails-1.webp" ] && git mv "images/startrails-1.webp" "images/star-trails-1.webp" || echo "skip (not found): images/startrails-1.webp"
[ -f "images/thumbs/startrails-1.webp" ] && git mv "images/thumbs/startrails-1.webp" "images/thumbs/star-trails-1.webp" || echo "skip (not found): images/thumbs/startrails-1.webp"
[ -f "images/startrails-2.webp" ] && git mv "images/startrails-2.webp" "images/star-trails-2.webp" || echo "skip (not found): images/startrails-2.webp"
[ -f "images/thumbs/startrails-2.webp" ] && git mv "images/thumbs/startrails-2.webp" "images/thumbs/star-trails-2.webp" || echo "skip (not found): images/thumbs/startrails-2.webp"
[ -f "images/startrails-3.webp" ] && git mv "images/startrails-3.webp" "images/star-trails-3.webp" || echo "skip (not found): images/startrails-3.webp"
[ -f "images/thumbs/startrails-3.webp" ] && git mv "images/thumbs/startrails-3.webp" "images/thumbs/star-trails-3.webp" || echo "skip (not found): images/thumbs/startrails-3.webp"
[ -f "images/startrails-4.webp" ] && git mv "images/startrails-4.webp" "images/star-trails-4.webp" || echo "skip (not found): images/startrails-4.webp"
[ -f "images/thumbs/startrails-4.webp" ] && git mv "images/thumbs/startrails-4.webp" "images/thumbs/star-trails-4.webp" || echo "skip (not found): images/thumbs/startrails-4.webp"
[ -f "images/Comet-1.webp" ] && git mv "images/Comet-1.webp" "images/comets-1.webp" || echo "skip (not found): images/Comet-1.webp"
[ -f "images/thumbs/Comet-1.webp" ] && git mv "images/thumbs/Comet-1.webp" "images/thumbs/comets-1.webp" || echo "skip (not found): images/thumbs/Comet-1.webp"
[ -f "images/Comet-2.webp" ] && git mv "images/Comet-2.webp" "images/comets-2.webp" || echo "skip (not found): images/Comet-2.webp"
[ -f "images/thumbs/Comet-2.webp" ] && git mv "images/thumbs/Comet-2.webp" "images/thumbs/comets-2.webp" || echo "skip (not found): images/thumbs/Comet-2.webp"
[ -f "images/Comet-3.webp" ] && git mv "images/Comet-3.webp" "images/comets-3.webp" || echo "skip (not found): images/Comet-3.webp"
[ -f "images/thumbs/Comet-3.webp" ] && git mv "images/thumbs/Comet-3.webp" "images/thumbs/comets-3.webp" || echo "skip (not found): images/thumbs/Comet-3.webp"

echo "Done. Review with: git status"
