#!/usr/bin/env python3
"""
generate-schema.py — bhapstar
-------------------------------------------------------------
Generates JSON-LD structured data from site-data.json and injects
it into the <head> of gallery.html and field_notes.html, so it can
never go stale relative to the content.

    python generate-schema.py

- gallery.html   gets an ImageObject per photo (every file in every
                  gallery-section entry's `images[]` array, or its
                  single `file`), so Google Images can match specific
                  searches (e.g. "Eagle Nebula photo") to a real photo
                  on the site rather than just the page as a whole.
- field_notes.html gets a BlogPosting per gallery-section entry, since
                  every gallery item also has a Field Notes write-up.
- Both blocks reference the same Person @id so the entity is
  consistent across pages.
- Re-running this is idempotent: it replaces the content between
  fixed HTML comment markers rather than appending duplicates.
"""

import json
import re
import sys
from datetime import datetime

DOMAIN = "https://bhapstar.com"
DATA = "site-data.json"
PERSON_ID = f"{DOMAIN}/#person"
PRINTS_PAGE = f"{DOMAIN}/prints.html"  # license terms + where to acquire an image

START = "<!-- AUTO-GENERATED STRUCTURED DATA — do not edit by hand, regenerated by generate-schema.py -->"
END = "<!-- END AUTO-GENERATED STRUCTURED DATA -->"

INSERT_AFTER = '<link rel="stylesheet" href="styles.css" />'


def to_iso(date_str):
    """Convert 'DD-MM-YYYY' to ISO 8601 'YYYY-MM-DD'. Falls back to None."""
    try:
        return datetime.strptime(date_str, "%d-%m-%Y").strftime("%Y-%m-%d")
    except (TypeError, ValueError):
        return None


def person_stub():
    return {
        "@type": "Person",
        "@id": PERSON_ID,
        "name": "Bhapinder Singh",
        "alternateName": "Bobby Singh",
        "url": DOMAIN,
    }


def url_for(path):
    return f"{DOMAIN}/{path}" if not path.startswith("http") else path


def gallery_images(entry):
    """Yield (file, alt, is_primary) for every photo belonging to an entry.
    Skips video entries (they carry posters that duplicate stills images
    elsewhere in the dataset, so including them would create duplicate
    ImageObjects for the same file)."""
    if entry.get("videos"):
        return
    images = entry.get("images")
    if images:
        for i, img in enumerate(images):
            if img.get("file"):
                yield img["file"], img.get("alt") or entry.get("alt"), i == 0
    elif entry.get("file"):
        yield entry["file"], entry.get("alt"), True


def build_gallery_graph(items):
    graph = [person_stub()]
    seen_files = set()

    for entry in items:
        if entry.get("section") != "gallery":
            continue
        iso_date = to_iso(entry.get("date"))
        for file, alt, is_primary in gallery_images(entry):
            if file in seen_files:
                continue
            seen_files.add(file)
            img_url = url_for(file)
            node = {
                "@type": "ImageObject",
                "@id": f"{img_url}#image",
                "contentUrl": img_url,
                "url": img_url,
                "name": entry.get("title") if is_primary else (alt or entry.get("title")),
                "description": entry.get("desc"),
                "creator": {"@id": PERSON_ID},
                "creditText": "Bhapinder Singh",
                "copyrightNotice": "© Bhapinder Singh",
                "license": PRINTS_PAGE,
                "acquireLicensePage": PRINTS_PAGE,
            }
            if alt:
                node["caption"] = alt
            if iso_date:
                node["datePublished"] = iso_date
            graph.append({k: v for k, v in node.items() if v is not None})

    return {"@context": "https://schema.org", "@graph": graph}


def build_field_notes_graph(items):
    graph = [person_stub()]

    for entry in items:
        if entry.get("section") != "gallery":
            continue
        slug = entry.get("slug")
        if not slug:
            continue
        iso_date = to_iso(entry.get("date"))
        page_url = f"{DOMAIN}/field_notes.html#{slug}"

        cover_file = None
        for file, _alt, is_primary in gallery_images(entry):
            if is_primary:
                cover_file = file
                break

        node = {
            "@type": "BlogPosting",
            "@id": page_url,
            "headline": entry.get("title"),
            "description": entry.get("intro") or entry.get("desc"),
            "image": url_for(cover_file) if cover_file else None,
            "author": {"@id": PERSON_ID},
            "publisher": {"@id": PERSON_ID},
            "mainEntityOfPage": {"@type": "WebPage", "@id": page_url},
            "keywords": ", ".join(entry.get("tags", [])) or None,
        }
        if iso_date:
            node["datePublished"] = iso_date
            node["dateModified"] = iso_date

        graph.append({k: v for k, v in node.items() if v is not None})

    return {"@context": "https://schema.org", "@graph": graph}


def inject(html_path, graph):
    with open(html_path, "r", encoding="utf-8") as f:
        html = f.read()

    block = (
        f"{START}\n"
        f'  <script type="application/ld+json">\n'
        f"{json.dumps(graph, indent=2, ensure_ascii=False)}\n"
        f"  </script>\n"
        f"  {END}"
    )

    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(html):
        new_html = pattern.sub(block, html)
    else:
        anchor = INSERT_AFTER
        if anchor not in html:
            print(f"  ! Could not find insertion anchor in {html_path}, skipping.")
            return
        new_html = html.replace(anchor, f"{anchor}\n  {block}", 1)

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(new_html)

    print(f"  Updated {html_path} ({len(graph['@graph']) - 1} entities + Person)")


def main():
    try:
        with open(DATA, "r", encoding="utf-8") as f:
            items = json.load(f)
    except FileNotFoundError:
        print(f"Could not find {DATA}", file=sys.stderr)
        sys.exit(1)

    print("Building gallery ImageObject graph...")
    inject("gallery.html", build_gallery_graph(items))

    print("Building Field Notes BlogPosting graph...")
    inject("field_notes.html", build_field_notes_graph(items))


if __name__ == "__main__":
    main()
